"$schema" = 'https://starship.rs/config-schema.json'

format = """
$username\
$hostname\
$directory\
$git_branch\
$git_state\
$git_status\
$line_break\
$character\
"""

right_format = """
$python\
$nodejs\
$golang\
$rust\
$php\
$java\
$kotlin\
$haskell\
$c\
$conda\
$cmd_duration\
$time\
"""

[username]
show_always = false
format = "[$user@]($style)"
style_user = "bold white"
style_root = "bold red"

[hostname]
ssh_only = true
format = "[$hostname ]($style)"
style = "bold white"

[directory]
format = "[$path]($style) "
style = "blue"
truncation_length = 4
truncation_symbol = "../"
truncate_to_repo = false

[git_branch]
symbol = " "
format = "[$symbol$branch]($style) "
style = "bold yellow"

[git_state]
format = "[($state( $progress_current/$progress_total))]($style) "
style = "bright-black"
rebase = ""
merge = ""
revert = "󰕌"
cherry_pick = ""
bisect = ""
am = ""
am_or_rebase = " or "

[git_status]
format = "[$all_status$ahead_behind]($style)"
style = "red"
ahead = "⇡${count} "
behind = "⇣${count} "
conflicted = "~${count} "
deleted = "✘${count} "
diverged = "⇣${behind_count} ⇡${ahead_count} "
modified = "!${count} "
renamed = "»${count} "
staged = "+${count} "
stashed = "*${count} "
untracked = "?${count} "
up_to_date = ""

[python]
symbol = " "
format = '[${pyenv_prefix}(${version} )(\($virtualenv\) )$symbol]($style) '
style = "green"

[nodejs]
symbol = " "
format = "[$version $symbol]($style) "
style = "green"

[golang]
symbol = " "
format = "[$version $symbol]($style) "
style = "green"

[rust]
symbol = " "
format = "[$version $symbol]($style) "
style = "green"

[php]
symbol = " "
format = "[$version $symbol]($style) "
style = "green"

[java]
symbol = " "
format = "[$version $symbol]($style) "
style = "green"

[kotlin]
symbol = " "
format = "[$version $symbol]($style) "
style = "green"

[haskell]
symbol = " "
format = "[$version $symbol]($style) "
style = "green"

[c]
symbol = " "
format = "[$version $symbol]($style) "
style = "green"

[conda]
symbol = " "
format = "[$environment $symbol]($style) "
style = "green"
ignore_base = true

[cmd_duration]
show_milliseconds = true
min_time = 0
format = "[$duration ]($style) "
style = "dimmed white"

[time]
disabled = false
time_format = "%H:%M"
format = "[$time 󰥔]($style)"
style = "dimmed white"

[line_break]
disabled = false

[character]
success_symbol = "[>](bold green)"
error_symbol = "[>](bold red)"
vimcmd_symbol = "[<](bold green)"
vimcmd_replace_one_symbol = "[<](bold yellow)"
vimcmd_replace_symbol = "[<](bold yellow)"
vimcmd_visual_symbol = "[<](bold blue)"
